try:
  1/0
 
except Exception as err:
  print("Error:", err)